# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_digit', models.CharField(blank=True, max_length=7, null=True)),
                ('second_digit', models.CharField(blank=True, max_length=7, null=True)),
                ('third_digit', models.CharField(blank=True, max_length=7, null=True)),
                ('fourth_digit', models.CharField(blank=True, max_length=7, null=True)),
                ('fifth_digit', models.CharField(blank=True, max_length=7, null=True)),
                ('sixth_digit', models.CharField(blank=True, max_length=7, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
