# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankuser',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
