# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_auto_20160408_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
