# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_auto_20160408_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
