# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_loginlog_registerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='BankUser_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankuser',
            name='number_of_logins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
