# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_auto_20160418_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlog',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
