# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_auto_20160418_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankuser',
            name='dob',
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
