# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingSystem', '0002_auto_20160403_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('Cr', 'Credit'), ('Db', 'Debit')], max_length=2, null=True),
        ),
    ]
