# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingSystem', '0003_auto_20160408_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
